### ISSUE TITLE
Bug for long arrays of strings in MATLAB but not Octave

### ISSUE THREAD

**Issue by mathieuboudreau** [vatlab/sos-matlab#9]
Hi,

I just fell on this bug.

Example
* Code: https://github.com/mathieuboudreau/sos_matlab_bug
* MyBinder session: https://mybinder.org/v2/gh/mathieuboudreau/sos_matlab_bug/master?filepath=Octave.ipynb

I have this array of long strings (in this example, I've saved in a *.mat file), and when I'm in Octave I can transfer it to Python without issue:

<img width="996" alt="Capture d’écran 2020-05-20 à 21 21 48" src="https://user-images.githubusercontent.com/1421029/82512729-7e966900-9aeb-11ea-9106-c6cf703524eb.png">

<img width="996" alt="Capture d’écran 2020-05-20 à 21 21 52" src="https://user-images.githubusercontent.com/1421029/82512737-82c28680-9aeb-11ea-99dc-a7000cc3f0d0.png">

However, when running using MATLAB, it errors:

<img width="1055" alt="Capture d’écran 2020-05-20 à 21 26 06" src="https://user-images.githubusercontent.com/1421029/82512765-97068380-9aeb-11ea-814d-b244da150eef.png">

<img width="1055" alt="Capture d’écran 2020-05-20 à 21 26 10" src="https://user-images.githubusercontent.com/1421029/82512770-9b32a100-9aeb-11ea-9432-9cc6fde23466.png">

It looks to me that it's because for some reason, in this case, if the total number of characters stored in the array + your `r"""` calls exceed 2048 characters then it is cut off somewhere in the SoS/Python code (I copy-pasted the relevant text in the error, and calculated the number of characters, and it's really close to 2048).

If I remove two of the array items from that example, it now can be transferred from MATLAB to Python:

<img width="1055" alt="Capture d’écran 2020-05-20 à 21 39 48" src="https://user-images.githubusercontent.com/1421029/82512835-d208b700-9aeb-11ea-9a8f-f14b57fb9ba1.png">

<img width="1055" alt="Capture d’écran 2020-05-20 à 21 39 57" src="https://user-images.githubusercontent.com/1421029/82512840-d6cd6b00-9aeb-11ea-96cd-08cebb669444.png">

Any clue if this bug is fixable?

**Comment by BoPeng** [comment]
I will have to check if there is MATLAB somewhere... 

But to debug, you can first

1. In matlab, run `sos_py_repr` and get an expression for the variable.
2. Check if the expression is executable in Python. If it is not, check `sos_py_repr.m`. Otherwise I will have to look into the sos side.

**Comment by mathieuboudreau** [comment]
Great, thanks as always @BoPeng !

There is this service called CodeOcean that lets you run Jupyter Notebooks and provides a MATLAB license (with a limited amount of hours per month) for free: https://codeocean.com

I was able to get SoS working on there - I recorded a video (meant for internal uses, but I'll share it here anyways) of me going through the instructions to do so: https://www.youtube.com/watch?v=umFzPnFNu1M

Here was the Dockerfile and postInstall files I used for that setup:

Dockerfile: https://gist.github.com/mathieuboudreau/9706ebf2d1e273e712be8c3c144ff114
postInstall: https://gist.github.com/mathieuboudreau/e82caee419cadd61e6a6a8f77e22e1c7

The only hiccup with CodeOcean is that it freezes if you try to create a new SoS notebook - so you have to upload an existing one and then you can edit it from that point on.

**Comment by mathieuboudreau** [comment]
I checked the command you suggested, and it appears to show (see below) the entire content of the array and isn't cut off like the error within sos-python shows in one of the above screenshots.

<img width="1026" alt="Capture d’écran 2020-05-21 à 01 07 37" src="https://user-images.githubusercontent.com/1421029/82520832-b27b8980-9aff-11ea-94ec-d7058bee8267.png">

**Comment by mathieuboudreau** [comment]
So likely whatever takes this representation and converts it within python cuts it off after ~2048 characters.

**Comment by mathieuboudreau** [comment]
Dug into as far as I could.

From what it looks like for me, the command `display(sos_py_repr(imagePathList))` as used here:

https://github.com/vatlab/sos-matlab/blob/4c0af397aa9098ea27a6314d4d0cba79aaec1cf0/src/sos_matlab/kernel.py#L136

returns the full list of strings as an output when **I** call it in a MATLAB cell, whereas the response from the SoS kernel here:

https://github.com/vatlab/sos-matlab/blob/4c0af397aa9098ea27a6314d4d0cba79aaec1cf0/src/sos_matlab/kernel.py#L137-L138

returns an incomplete version (only the first 2048 characters) when run in MATLAB. I tried to dig in to the sos-notebook kernel code, but I'm not able to understand it enough to debug further.

**Comment by BoPeng** [comment]
Got hold of MATLAB, and found that

```
%capture
display(sos_py_repr(imagePathList))
```

```
[('stream',
  {'name': 'stdout',
   'text': '[r"""20200121_matthewgrechsollars_ICL_NIST/20200121_matthewgrechsollars_ICL_NIST_Magnitude.nii.gz""",r"""20200121_matthewgrechsollars_ICL_NIST/20200121_matthewgrechsollars_ICL_NIST_Magnitude.nii.gz""",r"""20200121_matthewgrechsollars_ICL_NIST/20200121_matthewgrechsollars_ICL_NIST_Phase.nii.gz""",r"""20200124_siyuanhu_casewestern_NIST/20200124_siyuanhu_casewestern_NIST.nii.gz""",r"""20200203_iveslevesque_muhc_mgh_NIST/20200203_iveslevesque_muhc_mgh_NIST.nii.gz""",r"""20200204_mrel_usc_NIST/20200204_mrel_usc_GE3T_MR1_NIST.nii.gz""",r"""20200204_mrel_usc_NIST/20200204_mrel_usc_GE3T_MR2_NIST.nii.gz""",r"""20200204_mrel_usc_NIST/20200209_mrel_usc_GE3T_MR1_NIST.nii.gz""",r"""20200204_mrel_usc_NIST/20200209_mrel_usc_GE3T_MR1_NIST_TR10sec.nii.gz""",r"""20200204_mrel_usc_NIST/20200209_mrel_usc_GE3T_MR2_NIST.nii.gz""",r"""20200204_mrel_usc_NIST/20200209_mrel_usc_GE3T_MR2_NIST_TR10sec.nii.gz""",r"""20200210_guillaumegilbert_muhc_NIST/20200210_guillaumegilbert_muhc_NIST_Magnitude.nii.gz""",r"""20200210_guillaumegilbert_muhc_NIST/20200210_guillaumegilbert_muhc_NIST_Real.nii.gz""",r"""20200210_guillaumegilbert_muhc_NIST/20200210_guillaumegilbert_muhc_NIST_Imaginary.nii.gz""",r"""20200225_CStehningPhilipsClinicalScienceGermany_NIST/Aachen_MR1_magnitude.nii.gz""",r"""20200225_CStehningPhilipsClinicalScienceGermany_NIST/Aachen_MR1_real.nii.gz""",r"""20200225_CStehningPhilipsClinicalScienceGermany_NIST/Aachen_MR1_imag.nii.gz""",r"""20200225_CStehningPhilipsClinicalScienceGermany_NIST/Berlin_MR1_magnitude.nii.gz""",r"""20200225_CStehningPhilipsClinicalScienceGermany_NIST/Berlin_MR1_real.nii.gz""",r"""20200225_CStehningPhilipsClinicalScienceGermany_NIST/Berlin_MR1_imag.nii.gz""",r"""20200225_CStehningPhilipsClinicalScienceGermany_NIST/Bonn_MR1_magnitude.nii.gz""",r"""20200225_CStehningPhilipsClinicalScienceGermany_NIST/Cologne_MR1_magnitude.nii.gz""",r"""20200225_CStehningPhilipsClinicalScienceGermany_NIST/Berlin_MR1_real.nii.gz""",r"""20200225_CStehningPhilipsClinicalScienceGermany_NIST/Berlin_MR1_imag.nii.gz""",r"""20200227_karaku'}),
 ('stream',
  {'name': 'stdout',
   'text': 'zu_polymtl_NIST/20191213_UNF/20191213_karakuzu_UNF_NIST_FS.nii.gz""",r"""20200227_karakuzu_polymtl_NIST/20200227_MNI/20200227_karakuzu_mni_NIST_FS.nii.gz""",]\n'})]
```

So basically MATLAB decides to use two messages to print the output. SoS assumed there is only one and missed the second.

**Comment by BoPeng** [comment]
> I tried to dig in to the sos-notebook kernel code, but I'm not able to understand it enough to debug further.

Basically `get_response` sends the code to the kernel and captures all output, just like what the `%capture` magic does in the above example, but with parameters to just return the messages of interest. The function is described in detail [here](https://vatlab.github.io/sos-docs/doc/user_guide/language_module.html). 

Then the language module will assemble the output from the kernel and in this case calls `eval(expr)` to create the Python object.

**Comment by BoPeng** [comment]
I just released sos-matlab 0.18.4 for this fix.

**Comment by mathieuboudreau** [comment]
Thanks for digging into this bug so quickly @BoPeng .

Unfortunately, the bug still appears to me on my end after I upgraded `sos-matlab` to 0.18.4.  Did you try downloading my example and running it?  https://github.com/mathieuboudreau/sos_matlab_bug

**Comment by BoPeng** [comment]
Yes. I did.

<img width="1889" alt="Screen Shot 2020-05-21 at 9 26 50 AM" src="https://user-images.githubusercontent.com/9889312/82569029-4885d300-9b45-11ea-93df-54f8ba6d1543.png">

![image](https://user-images.githubusercontent.com/9889312/82569086-5f2c2a00-9b45-11ea-94a2-48b2fbae7924.png)

![image](https://user-images.githubusercontent.com/9889312/82569154-7539ea80-9b45-11ea-8f39-2eceecb02e55.png)

**Comment by mathieuboudreau** [comment]
Hmm, I found something weird - I'll report back shortly. Might be an issue on my end

**Comment by BoPeng** [comment]
You might have multiple versions of `sos-matlab`. Sometimes I have to go to `site-packages` and clean up there.

**Comment by mathieuboudreau** [comment]
Yes, that's what happened. I am running in a conda virtual environment, but I also accidentally had sos-matlab installed in my `base` env as well - an older version.

It appears that while a pure Python notebook uses the `sos-matlab` module that's in my conda environment, the Python environment in an SoS notebooks uses the `sos-matlab` package from the `base` environment instead of the virtual environment that's activated.

SoS notebook:

<img width="1026" alt="Capture d’écran 2020-05-21 à 12 05 05" src="https://user-images.githubusercontent.com/1421029/82570102-bb01ad80-9b5b-11ea-83fb-80c5389f383e.png">


Pure Python notebook:


<img width="1086" alt="Capture d’écran 2020-05-21 à 12 05 15" src="https://user-images.githubusercontent.com/1421029/82570116-bf2dcb00-9b5b-11ea-9c61-aff6b2a59d54.png">

Does SoS not support packages from activate conda environments? Or is this just a funny override where it'll use the base package before the conda-installed environments?

**Comment by mathieuboudreau** [comment]
Regardless, the bug is resolved now for me. Thank you immensely @BoPeng  - you're a superstar! I really appreciate all your help - hope all is well with you.
